<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SAI-PC" name="allClassFilesHere.Test1_Sikuli2" tests="1" failures="0" timestamp="17 May 2020 12:53:06 GMT" time="9.025" errors="1">
  <testcase name="handlefileUpload" time="9.025" classname="allClassFilesHere.Test1_Sikuli2">
    <error type="org.sikuli.script.FindFailed" message="can not find D:\March22nd_2020\sikuliproject\src\sikuli_locators\ImageFile.PNG in S(0)[0,0 1366x768]">
      <![CDATA[FindFailed: can not find D:\March22nd_2020\sikuliproject\src\sikuli_locators\ImageFile.PNG in S(0)[0,0 1366x768]
  Line 2189, in file Region.java

at org.sikuli.script.Region.handleFindFailedShowDialog(Region.java:2189)
at org.sikuli.script.Region.handleFindFailed(Region.java:2134)
at org.sikuli.script.Region.wait(Region.java:2546)
at org.sikuli.script.Region.find(Region.java:2205)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3067)
at org.sikuli.script.Region.doubleClick(Region.java:3581)
at org.sikuli.script.Region.doubleClick(Region.java:3566)
at allClassFilesHere.Test1_Sikuli2.handlefileUpload(Test1_Sikuli2.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- handlefileUpload -->
</testsuite> <!-- allClassFilesHere.Test1_Sikuli2 -->
